### ISSUE TITLE
Store files server-side instead of sending them by email

### ISSUE THREAD

**Issue by Alwaysin** [whitesmith/hawkpost#271]
This software is typically what I need to use but I would need a few modifications to be able to do so.

First and foremost, would it be possible to store the files server-side, instead of sending them by email?
We want selected users to be able to access the content of the boxes they have created, to download the file when needed and that the file deletes itself when the time is over.

**Comment by dethos** [comment]
Hello, regarding the part of several users being able to access/receive the encrypted data that is submitted on the box, we already have part of that feature implemented but is not active (we have to finish it first, you can follow it or help here #5 )

The part of the storage is more tricky, since this project is not intended to handle the storage of this encrypted blobs or even store anything else. One solution to your problem could be to add an integration (#41) with another service/app that could be used as delivery method instead of email.

The first part we intent to have it ready soon, the second is still in discussion and with some help we can start working on it as well.
