### ISSUE TITLE
Docker installation with Compose doesn't work following README

### ISSUE THREAD

**Issue by lpulley** [whitesmith/hawkpost#296]
Hi all!

I've been trying to install Hawkpost with Docker Compose following the instructions in the README but I'm having issues. The build doesn't seem to be installing pipenv correctly and I'm getting the following:

```
Step 8/11 : RUN pipenv install --dev
 ---> Running in e677cf55a8e8 
Warning: Python 3.6 was not found on your system… 
You can specify specific versions of Python with: 
  $ pipenv --python path/to/python
The command '/bin/sh -c pipenv install --dev' returned a non-zero code: 1
```

Is Docker installation actively supported for Hawkpost?

**Comment by dethos** [comment]
@lpulley We have an open PR that fixes that issue. Basically the `Dockerfile` does not set a specific python 3 version. At the time it worked because the last version was 3.6, but nowadays it fetches `python:3.7` image and the version set on the `Pipfile` is not available on the image.

If you can't wait for @pjaneiro to merge the PR, you just need to make [this one line change](https://github.com/whitesmith/hawkpost/pull/295/files#diff-08bc83c6a89d6b335935cbb22c40f36eR1) to solve your issue.

**Comment by pjaneiro** [comment]
Closing this since #295 was merged in the meantime

**Comment by lpulley** [comment]
Just saw this @dethos. Thanks much for the quick response! I'll give this another go ASAP.
